DROP TABLE MEMBER
CASCADE CONSTRAINTS;

CREATE TABLE "HR"."MEMBER" 
   (	"MEMBERID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PWD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PHONENUM" NUMBER(20,0) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"TRAINERID" VARCHAR2(20 BYTE), 
	"PROFILEIMG" VARCHAR2(50 BYTE), 
	"AGE" NUMBER(5,0), 
	"HEIGHT" NUMBER(5,0), 
	"GWEIGHT" NUMBER(5,0), 
	"MEMLEVEL" NUMBER(30,0) NOT NULL ENABLE, 
	"MEMTYPE" NUMBER(3,0) NOT NULL ENABLE, 
	"GYMNAME" VARCHAR2(100 BYTE), 
	"TRAINERCONTENT" VARCHAR2(400 BYTE), 
	"WEIGHT" NUMBER(5,0), 
	 CONSTRAINT "MEMBER_PK" PRIMARY KEY ("MEMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
SELECT * FROM MEMBER;
INSERT INTO MEMBER

SELECT * FROM STAFF;


INSERT INTO STAFF (ID, NAME, PHONENUMBER) 
VALUES(CCC,CCC,02-355)